### ISSUE TITLE
Exception handling: ‘Rule browser’ freezes 

### ISSUE THREAD

**Issue by a-pika** [yawlfoundation/yawl#596]
[combiningRules.xrs.gz](https://github.com/yawlfoundation/yawl/files/486527/combiningRules.xrs.gz)
[combiningRules.yawl.gz](https://github.com/yawlfoundation/yawl/files/486526/combiningRules.yawl.gz)
When the ‘Rule Browser’ is opened for the attached specification, and rule types are selected sequentially, after the last rule type is selected from the list, the window freezes:
![image](https://cloud.githubusercontent.com/assets/14101966/18737522/d13479f6-80d5-11e6-83a2-05bd8d83230e.png)

**Comment by yawlfoundation** [comment]
fixed in latest build (705)

**Comment by a-pika** [comment]
The issue still persists after updating the Engine and the Editor to the latest version. 
Clarification: if 'Workitem post-constraint violation' rule type is selected immediately after opening the Rule browser, the browser does not freeze, it freezes when first 'Workitem pre-constraint violation' is selected and then 'Workitem post-constraint violation' rule type is selected.
